/*Problem Description:

A neighborhood bakery wants a summary of total units sold and total revenue for each product category, to help decide what to bake more of.

The result must contain the following columns:

category — the product category
total_units_sold — total units sold across all sales of that category
total_revenue — total revenue generated by that category, rounded to 2 decimals*/

-- Write your query for: 422. Total Sales By Category | @Amazon
select Category,
sum(units_sold) as total_units_sold,
sum(units_sold*unit_price) as total_revenue
from bakery_sales group by Category
order by total_revenue desc
